(system "python python/graffle_clips.py graffle/test.graffle >graffle/test.facts")
(clear)
(defmodule MAIN (export ?ALL))
(load "modules/plist_model.clp")
(load-facts "graffle/test.facts")
(load "modules/graffle_model.clp")
(load "modules/plist_2_graffle.clp")
(focus PLIST->GRAFFLE)
(run)
(focus GRAFFLE)
(facts)
